version: '3.8'

services:
  db:
    image: postgis/postgis:17-3.5
    container_name: postgres_new
    restart: always
    environment:
      POSTGRES_DB: postgres_new
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5434:5432
    volumes:
      - pg_new:/var/lib/postgresql/data
volumes:
  pg_new:
