-- --liquibase formatted sql
-- --changeset userName:1
DROP TABLE IF EXISTS message;

CREATE TABLE message (
                         messageId BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         content TEXT NOT NULL,
                         messageType VARCHAR(255),
                         senderId BIGINT NOT NULL,
                         recipientId BIGINT NOT NULL,
                         timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Add foreign key constraints
ALTER TABLE message
    ADD CONSTRAINT fk_message_sender FOREIGN KEY (senderId) REFERENCES users(id) ON DELETE CASCADE;

ALTER TABLE message
    ADD CONSTRAINT fk_message_recipient FOREIGN KEY (recipientId) REFERENCES users(id) ON DELETE CASCADE;