--liquibase formatted sql
--changeset userName:1
DROP TABLE IF EXISTS testEntity;
CREATE TABLE testEntity (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

insert into testEntity(name) values( 'TestEntity 1');
insert into testEntity(name) values( 'TestEntity 2');
insert into testEntity(name) values( 'TestEntity 3');


DROP TABLE IF EXISTS users;
CREATE TABLE users(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firstName VARCHAR(255) NOT NULL,
    lastName VARCHAR(255) NOT NULL,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    organization VARCHAR(255)
);

-- auto-generated definition
create table message
(
    messageid   bigint generated by default as identity
        primary key,
    content     text   not null,
    messagetype varchar(255),
    senderid    bigint not null
        constraint fk_message_sender
            references users
            on delete cascade,
    recipientid bigint not null
        constraint fk_message_recipient
            references users
            on delete cascade,
    timestamp   timestamp default CURRENT_TIMESTAMP
);

