--liquibase formatted sql
--changeset userName:1
DROP TABLE IF EXISTS entity;
CREATE TABLE entity (
                        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR(255) NOT NULL
);
insert into entity(name) values( 'Entity 1');
insert into entity(name) values( 'Entity 2');
insert into entity(name) values( 'Entity 3');