CREATE EXTENSION IF NOT EXISTS postgis;

DROP TABLE IF EXISTS locations CASCADE;
DROP TABLE IF EXISTS location_types CASCADE;

CREATE TABLE location_types (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                typename VARCHAR(255) NOT NULL UNIQUE,
                                description TEXT
);

INSERT INTO location_types (typename, description)
VALUES
    ('Victim', 'Poszkodowany'),
    ('Volunteer', 'Wolontariusz'),
    ('Aid', 'Organizacja Pomocowa'),
    ('Authority', 'Przedstawiciel Władz'),
    ('Area', 'Obszar katastrofy');

CREATE TABLE locations (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           name VARCHAR(255) NOT NULL,
                           locationtype INT NOT NULL,
                           coordinates geometry(Point, 4326),
                           disasterarea geometry(Polygon, 4326),
                           CONSTRAINT fk_location_type FOREIGN KEY (locationtype)
                               REFERENCES location_types (id) ON DELETE CASCADE
);


INSERT INTO locations (name, locationtype, coordinates)
VALUES
    ('Student Debil', 1, ST_SetSRID(ST_MakePoint(19.455646, 51.746985), 4326));


INSERT INTO locations (name, locationtype, disasterarea)
VALUES
    ('Sesja', 4, ST_SetSRID(ST_GeomFromText('POLYGON((19.45 51.74, 19.46 51.74, 19.46 51.75, 19.45 51.75, 19.45 51.74))'), 4326));
/*
DROP TABLE IF EXISTS locations CASCADE;
DROP TABLE IF EXISTS location_types CASCADE;
DROP TABLE IF EXISTS area_types CASCADE;


CREATE TABLE location_types (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    typename VARCHAR(255) NOT NULL UNIQUE,
    description TEXT
);

INSERT INTO location_types (typename, description)
VALUES
    ('Victim', 'Poszkodowany'),
    ('Volunteer', 'Wolontariusz'),
    ('Aid', 'Organizacja Pomocowa'),
    ('Authority', 'Przedstawiciel Władz');

CREATE TABLE area_types (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    typename VARCHAR(255) NOT NULL UNIQUE,
    description TEXT
);

INSERT INTO area_types (typename, description)
VALUES
    ('Disaster', 'Obszar katastrofy'),
    ('Warehouse', 'Magazyn');

CREATE TABLE locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    pointtype INT,
    areatype INT,
    coordinates geometry(Point, 4326),
    area geometry(Polygon, 4326),
    CONSTRAINT fk_point_type FOREIGN KEY (pointtype)
        REFERENCES location_types (id) ON DELETE CASCADE,
    CONSTRAINT fk_area_type FOREIGN KEY (areatype) REFERENCES area_types (id) ON DELETE CASCADE,
    CONSTRAINT check_exclusive_types CHECK (pointtype IS NULL OR areatype IS NULL)
);


INSERT INTO locations (name, pointtype, coordinates)
VALUES
    ('Student Debil', 1, ST_SetSRID(ST_MakePoint(19.455646, 51.746985), 4326));


INSERT INTO locations (name, areatype, area)
VALUES
    ('Sesja', 1, ST_SetSRID(ST_GeomFromText('POLYGON((19.45 51.74, 19.46 51.74, 19.46 51.75, 19.45 51.75, 19.45 51.74))'), 4326));
*/--DROP TABLE IF EXISTS location_types CASCADE;
/*
CREATE TABLE location_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    typename VARCHAR(255) NOT NULL UNIQUE,
    description TEXT
);

INSERT INTO location_types (typename, description)
VALUES
    ('Point', 'Poszkodowany');

SELECT * FROM locations;

--DROP TABLE IF EXISTS locations CASCADE;

CREATE TABLE locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    location_type INTEGER NOT NULL,
    latitude DECIMAL NOT NULL,
    longitude DECIMAL NOT NULL
);*/

-- INSERT INTO locations (name, location_type_id, latitude, longitude)
-- VALUES
--     ('PŁ', 1, 51.7471523, 19.4517336);
-- DROP TABLE IF EXISTS locations CASCADE;
--
-- CREATE TABLE locations (
--     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--     name VARCHAR(255) NOT NULL,
--     location_type_id BIGINT NOT NULL,
--     coordinates geometry(Point, 4326) NOT NULL,
--     CONSTRAINT fk_location_type FOREIGN KEY (location_type_id)
--         REFERENCES location_types (id) ON DELETE CASCADE
-- );
--
-- DROP TABLE IF EXISTS routes CASCADE;
--
-- CREATE TABLE routes (
--     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--     name VARCHAR(255) NOT NULL,
--     path geometry(LineString, 4326) NOT NULL
-- );